global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'aurora-trading-system'
    static_configs:
      - targets: ['aurora:5000']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
